name = "map-managed-environment"
language = "tinygo"
type = "component"
version = "0.1.0"

[component]
wit_world = "map-managed-environment"
wasm_target = "wasm32-wasi-preview2"
destination = "build/map-managed-environment_s.wasm"
